name: Deploy to Staging

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Staging
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages (staging)
        run: npx wrangler pages deploy dist --project-name=alex-miller --branch=staging
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: 27cafbbee6f8e1db0d9499405d4755c1
